openapi: 3.0.1
info:
  title: Appointment BACK
  description: Esta API expone los endpoint para registrar tareas programadas para
    una Clínica de Chile.
  contact:
    name: Hugo Cárcamo
    url: https://portfolio.ultra-neo.com
    email: hugomode@gmail.com
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Server URL in Development environment
- url: https://clinic-appointment.ultra-neo.com
  description: Server URL in Production environment
tags:
- name: Indisa Controller
  description: Endpoints para administrar las citas de la clinica Indisa
paths:
  /api/v1/clinic/indisa/appointments:
    get:
      tags:
      - Indisa Controller
      operationId: findAllTaskProgram
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskProgram'
    post:
      tags:
      - Indisa Controller
      summary: Crea una tarea programada
      description: Crear un registro de búsqueda de cita para una tarea programada
      operationId: createTaskProgram
      requestBody:
        content:
          application/json:
            schema:
              type: string
              description: Input body para crear una tarea
              example:
                previsionID: 67
                startDate: 2024-01-15
                endDate: 2024-01-20
                specialityID: 226
                doctorsIDs:
                - 14655
                - 12375
                office: PROVIDENCIA
                emails:
                - email1@example.com
                - email2@example.com
        required: true
      responses:
        "500":
          description: Internal Server Error
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskProgram'
  /api/v1/clinic/indisa/appointments/{id}:
    get:
      tags:
      - Indisa Controller
      operationId: getTaskProgramById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskProgram'
    patch:
      tags:
      - Indisa Controller
      operationId: updateTaskProgramActive
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: boolean
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskProgram'
  /api/v1/clinic/indisa/appointments/{id}/doctors/{doctorId}:
    patch:
      tags:
      - Indisa Controller
      operationId: updateTaskProgramActive_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: doctorId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: boolean
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskProgram'
  /api/v1/clinic/indisa/external/appointments:
    get:
      tags:
      - Indisa Controller
      summary: Buscar cita en la clínica
      description: Busca una cita para un doctor con la API de la clínica Indisa
      operationId: invokeExternalService
      parameters:
      - name: agendaID
        in: query
        description: identificador único de la sesión para usar api externa
        required: true
        schema:
          type: string
        example: 65af298ffc465ea2f7dedb49
      - name: specialityID
        in: query
        description: ID de la Especialidad médica
        required: true
        schema:
          type: string
        example: 226
      - name: doctorID
        in: query
        description: 'ID del doctor asociada a la sucursal '
        required: true
        schema:
          type: string
        example: 14655
      - name: office
        in: query
        description: sucursal de la Clínica
        required: true
        schema:
          type: string
        example: PROVIDENCIA
      responses:
        "500":
          description: Internal Server Error
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndisaCalendarOutputModel'
        "404":
          description: Not Found
components:
  schemas:
    AppointmentFound:
      type: object
      properties:
        doctorId:
          type: integer
          format: int32
        taskProgram:
          $ref: '#/components/schemas/TaskProgram'
        notify:
          type: boolean
        appointmentFoundId:
          type: integer
          format: int64
    Clinic:
      type: object
      properties:
        clinicId:
          type: integer
          format: int32
        name:
          type: string
    TaskProgram:
      type: object
      properties:
        taskProgramId:
          type: integer
          format: int64
        clinic:
          $ref: '#/components/schemas/Clinic'
        doctors:
          type: array
          items:
            $ref: '#/components/schemas/AppointmentFound'
        previsionId:
          type: integer
          format: int32
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        officeName:
          type: string
        speciality:
          type: integer
          format: int32
        emails:
          type: array
          items:
            type: string
        creationDate:
          type: string
          format: date-time
        active:
          type: boolean
    IndisaCalendarOutputModel:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
        daysToShowOffer:
          type: integer
          format: int32
        firstDate:
          type: string
        isFirstDate:
          type: boolean
        status:
          type: string
        todayStr:
          type: string
        workingDates:
          type: array
          items:
            type: string
